---
- name: Install awstats package(s)
  apt:
    pkg: "{{ item }}"
    state: latest
    update_cache: yes
    default_release: "{{ awstats_default_release }}"
  with_items: "{{ awstats_packages }}"

- name: Move base awstats config
  command: "/bin/mv -f /etc/awstats/awstats.conf /etc/awstats/awstats.conf.dist"
  args:
    removes: "/etc/awstats/awstats.conf"

- name: Configure awstats.local.conf
  template:
    src: "local.conf.j2"
    dest: "/etc/awstats/awstats.conf.local"

- name: Create awstats config for site {{ item.name }}
  template:
    src: "site.conf.j2"
    dest: "/etc/awstats/awstats.{{ item.name }}.conf"
  with_items: "{{ awstats_site_configs }}"

